poke/urls.py
from django.urls import path

from . import views

app_name = 'poke'
urlpatterns = [
    path('', views.list_poke, name='index'), # adicione esta linha
    path('search/', views.search_poke, name='search'), # adicione esta linha
    path('create/', views.create_poke, name='create'), # adicione esta linha
    path('<int:poke_id>/', views.detail_poke , name='detail'), # adicione esta linha
    path('update/<int:poke_id>/', views.update_poke, name='update'),
    path('delete/<int:poke_id>/', views.delete_poke, name='delete'),
    path('<int:poke_id>/coment/', views.create_coment, name='coment'),
    path('categorys/', views.CategoryListView.as_view(), name='categorys'),
    path('category/<int:category_id>/', views.detail_category, name='category')

]

pokesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('poke/', include('poke.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

poke/models.py
# Create your models here.
from django.db import models
from django.conf import settings
from datetime import datetime

class Poke(models.Model):
    name = models.CharField(max_length=255)
    date = models. DateTimeField(auto_now_add=True)
    poster_url = models.URLField(max_length=200, null=True)
    content = models.TextField()

    def __str__(self):
        date_time = self.date.strftime("%m/%d/%Y")
        return f'{self.name} ({date_time})'


class Coment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models. DateTimeField(auto_now_add=True)
    poke = models.ForeignKey(Poke, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    
    name = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    poke = models.ManyToManyField(Poke)

    def __str__(self):
        return f'{self.name} descrição: {self.text}'

staticpages/models.py
from django.db import models

# Create your models here.

poke/forms.py
from django import forms

from django.forms import ModelForm
from .models import Poke, Coment


class PokeForm(ModelForm):
    class Meta:
        model = Poke
        fields = [
            'name',
            
            'poster_url',
            'content',
        ]
        labels = {
            'name': 'Título',
            
            'poster_url': 'URL do Poster',
            'content': 'Notícia',
        }

class ComentForm(ModelForm):
    class Meta:
        model = Coment
        fields = [
            'author',
            'text',
            
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

poke/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from .temp_data import poke_data
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Poke, Coment, Category
from .forms import PokeForm, ComentForm
from django.shortcuts import render, get_object_or_404
from django.views import generic


def detail_poke(request, poke_id):
    poke = get_object_or_404(Poke, pk=poke_id)
    context = {'poke': poke}
    return render(request, 'poke/detail.html', context)

def list_poke(request):
    poke_list = Poke.objects.all()

    context = {'poke_list': poke_list}
    return render(request, 'poke/index.html', context)

def search_poke(request):
    context = {}
    if request.GET.get('query', False):
        poke_list=[]
        search_term = request.GET['query'].lower()
        poke1_list = Poke.objects.filter(name__icontains=search_term)
        for i in range(len(poke1_list),0,-1):
            i-=1
            poke_list.append(poke1_list[i])
        context = {"poke_list": poke_list}
    return render(request, 'poke/search.html', context)

def create_poke(request):
    if request.method == 'POST':
        poke_name = request.POST['name']
        poke_poster_url = request.POST['poster_url']
        poke_content = request.POST['content']
        poke = Poke(name=poke_name,
                      poster_url=poke_poster_url,
                      content = poke_content )
        poke.save()
        return HttpResponseRedirect(
            reverse('poke:detail', args=(poke.id, )))
    else:
        form = PokeForm()
        context = {'form': form}
        return render(request, 'poke/create.html', context)

def update_poke(request, poke_id):
    poke = get_object_or_404(Poke, pk=poke_id)

    if request.method == "POST":
        poke.name = request.POST['name']
        poke_poster_url = request.POST['poster_url']
        poke.content = request.POST['content']
        poke.save()
        return HttpResponseRedirect(
            reverse('poke:detail', args=(poke.id, )))

    context = {'poke': poke}
    return render(request, 'poke/update.html', context)

def delete_poke(request, poke_id):
    poke = get_object_or_404(Poke, pk=poke_id)

    if request.method == "POST":
        poke.delete()
        return HttpResponseRedirect(reverse('poke:index'))

    context = {'poke': poke}
    return render(request, 'poke/delete.html', context)

def create_coment(request, poke_id):
    poke = get_object_or_404(Poke, pk=poke_id)
    if request.method == 'POST':
        form = ComentForm(request.POST)
        if form.is_valid():
            coment_author = form.cleaned_data['author']
            coment_text = form.cleaned_data['text']
            coment = Coment(author=coment_author,
                            text=coment_text,
                            poke=poke)
            
            coment.save()
            
            return HttpResponseRedirect(
                reverse('poke:detail', args=(poke_id, )))
    else:
        form = ComentForm()
    context = {'form': form, 'poke': poke}
    return render(request, 'poke/coment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'poke/categorys.html'


def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'poke/category.html', context)


def list_coment(request,poke_id):
    coment1_list = Coment.objects.filter(pk=poke_id)
    coment_list=[]
    for i in range(len(coment1_list),0,-1):
            i-=1
            coment_list.append(coment1_list[i])
    context = {'coment_list': coment_list}
    return render(request, 'poke/detail.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

poke/templates/poke/category.html
{% extends 'base.html' %}

{% block content %}
<article>
    <header>
        <h1>{{category.name}} :  </h1>
        <h3>{{ category.text }}</h3>
    </header>
    <div class="lista-de-cards">
        {% for poke in category.poke.all %}
        <div class="card">
            <a href="{% url 'poke:detail' poke.id %}"><img src="{{ poke.poster_url }}"
                    alt="Poster do filme {{ poke.name}}"></a>
            <p>{{ poke.name }} ({{ poke.date|date:"D d M Y"  }})</p>
        </div>
        {% endfor %}
    </div>
</article>

{% endblock content %}

poke/templates/poke/categorys.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Notícia</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}} : {{ category.text }} </h3>
        </header>
        <div class="lista-de-cards">
            {% for poke in category.poke.all|dictsortreversed:"date" %}
            <div class="card">
                <a href="{% url 'poke:category' category.id %}"><img src="{{ poke.poster_url }}"
                        alt="Poster do filme {{ poke.name}}"></a>
                <p>{{ poke.name }} ({{ poke.date|date:"D d M Y"  }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

   
</section>

{% endblock content %}

poke/templates/poke/coment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentário sobre {{ poke.name }} ({{ poke.date|date:"d M Y" }})</h2>

<form action="{% url 'poke:coment' poke.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'poke:detail' poke.id %}">Voltar para a página da notícia</a></p>
{% endblock content %}

poke/templates/poke/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'poke:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" value="{{ poke.name }}" />
    </p>
    <p>
        <label for=" id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{poke.poster_url}}" />
    </p>
    <p>
        <label for="id_content">Conteúdo:</label>
        <input type="text" name="content" id="id_content" value="{{ poke.content }}" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

poke/templates/poke/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'poke:delete' poke.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o Post "{{ poke.name }} ({{ poke.date|date:"D d M Y" }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

poke/templates/poke/detail.html
{% extends 'base.html' %}

{% block title %}
{{ poke.name }} ({{ poke.date }}
{% endblock title %}

{% block content %}
<h2>{{ poke.name }}</h2>

<section class="dados-de-filme">
    <img class="card" src="{{ poke.poster_url }}" alt="Poster do filme {{ poke.name}}">
    <ul>
        <li>Título: {{ poke.name }}</li>
        <li>Data: {{ poke.date|date:"D d M Y" }} </li>
        <li>Categorias:</li>
        {% if poke.category_set.all %}
            {% for category in poke.category_set.all %}
            <li><a href="{% url 'poke:category' category.id %}">{{ category.name }}-{{ category.text}} </a></li>
            {% endfor %}
        {% else %}
            <p>Ainda não pertence a nenhuma categoria</p>
        {% endif %}

        <li><a href="{% url 'poke:update' poke.id %}">Editar</a></li>
        <li><a href="{% url 'poke:delete' poke.id %}">Apagar</a></li>
        
        
    </ul>   
</section>
<p>{{ poke.content | safe }} </p>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ol>
        {% if poke.coment_set.all %}
            {% for coment in poke.coment_set.all|dictsortreversed:"date" %}
                <li reversed>
                    <figure>
                        <blockquote>
                            "{{ coment.text }}"
                        </blockquote>
                        <figcaption>—{{ coment.author }} ({{ coment.date|date:"SHORT_DATE_FORMAT" }} )
                    </figure>
                </li>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário.</p>
        {% endif %}
    </ol>

    <hr>

    <a href="{% url 'poke:coment' poke.pk %}"><button>Comente</button></a>
</section>
</section>

{% endblock content %}

poke/templates/poke/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'poke:search' %}">Buscar determindo assunto</a></p>
    <p>Está faltando algo? <a href="{% url 'poke:create' %}">Adicionar Novo Post</a></p>
</section>
{% if poke_list|dictsortreversed:"date" %}
<section class="lista-de-cards">
    {% for poke in poke_list|dictsortreversed:"date" %}
    
    <article class="card">
        <a href="{% url 'poke:detail' poke.id %}"><img src="{{ poke.poster_url }}"
            alt="Poster da Notícia {{ poke.name}}"></a> <!-- modifique esta linha -->
        <p>{{ poke.name }} ({{ poke.date|date:"D d M Y"  }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Post.</p>
{% endif %}

{% endblock content %}

poke/templates/poke/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'poke:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if poke_list %}
<section class="lista-de-cards">
    {% for poke in poke_list|dictsortreversed:"date" %}
    <article class="card">
        <img src="{{ poke.poster_url }}" alt="Poster do filme {{ poke.name}}">
        <p>{{ poke.name }} ({{ poke.date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

poke/templates/poke/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Post {{ poke.name }} ({{ poke.date}})</h2>
<form method="POST" action="{% url 'poke:update' poke.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" value="{{ poke.name }}" />
    </p>
    <p>
        <label for=" id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{poke.poster_url}}" />
    </p>
    <p>
        <label for="id_content">Conteúdo:</label>
        <input type="text" name="content" id="id_content" value="{{ poke.content }}" />
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h3>Sobre a franquia:</h3>

<img src="../../static/images/pokename.png" class="drawing">

<p>    
Pokémon é uma série de jogos eletrônicos desenvolvidos pela Game Freak e publicados pela Nintendo como parte da franquia de mídia Pokémon. Lançado pela primeira vez em 1996 no Japão para o console Game Boy, a principal série de jogos de RPGs, que continuou em cada geração em portáteis da Nintendo.
</p>
<h3>Sobre o anime:</h3>
<img src="../../static/images/pokemonAnime.png" class="drawing">
<p>
Os jogos são geralmente lançados em pares, sendo que cada um contém pequenas variações em relação ao outro. Enquanto a série principal consiste em RPGs, os spin-off abrangem outros gêneros, como RPG de ação, quebra-cabeça e jogos virtuais para animais de estimação.
</p>
<h3>Sobre os Jogos</h3>
<img src="../../static/images/allGames.jpg" class="drawing">
<p>
A partir de 24 de novembro de 2017 , mais de 300 milhões de jogos de Pokémon foram vendidos em todo o mundo, em 76 títulos. Isso faz de Pokémon a segunda franquia de jogos eletrônicos mais vendidas, atrás da própria franquia da Nintendo Mario.
</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1>Pokemon Basics</h1>

<p>Este site tem como objetivo juntar todas notícias em relação à Pokemon</p>
<p>Agradecemos a todos que colaborarem com postagens e ao aumentar o nosso Banco de dados</p>
{% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'pokemon_icon.png' %}"alt="logo" width="20%" height="20%"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul class="cabecalho">
                <li><a href="{% url 'poke:index' %}">Notícias</a></li>
                <li><a href="{% url 'poke:categorys' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>